version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./biblibra_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  api:
    image: biblibra/api:latest
  hasura:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8082:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  web:
    image: biblibra/web:latest
    ports:
      - "8081:80"
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
